### ISSUE TITLE
clarify difference between gateways and nodes

### ISSUE THREAD

**Issue by paidforby** [sudomesh/monitor#1]
Are gateways also nodes? Does the count of "nodes" include the count of "gateways?" Maybe a quick definitions of terms and links to further documentations would be useful?

**Comment by jhpoelen** [comment]
yep - gateway node and nodes. Please feel free to add description to webpage .

**Comment by jhpoelen** [comment]
gateways are nodes also

**Comment by paidforby** [comment]
someone took care of this
