### ISSUE TITLE
One bad 'node' from /nodes API (and db)

### ISSUE THREAD

**Issue by gobengo** [sudomesh/monitor#10]
https://peoplesopen.herokuapp.com/api/v0/nodes

Scroll down and/or look at the last one

```
{
timestamp: "2018-05-08T22:23:10.022Z",
nodeIP: ""
}
```

Actual: There is a node with nodeIP of empty string and no gatewayIP.
Expected: All nodes in this array have a truthy nodeIP and gatewayIP.

Other info
* I believe the bad data is in the JSON string in memcache
* I think this is due to faulty parsing in the /route-table endpoint.

I think I can fix it. Putting here to track.

**Comment by bennlich** [comment]
I got the urge :-P
