### ISSUE TITLE
unable to run locally

### ISSUE THREAD

**Issue by paidforby** [sudomesh/monitor#2]
README.md reads, "This assumes some local memcache instance running." I'm not sure what this means. Could we provide instructions for doing this or point to a link on how to do this?
Thanks!

**Comment by paidforby** [comment]
[instructions](https://devcenter.heroku.com/articles/memcachier#local-usage) don't seem to work for me, `Linux silverback 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux`,  
`memcached -v` produces no output and `foreman start` fails to find foreman command. Sorry @jhpoelen I'm not familiar with memcache or heroku, could you please provide more complete instructions. I'd like to resolve #1 let me if there is alternative to test my additions.

**Comment by jhpoelen** [comment]
@paidforby No need to apologize. I've never run this locally, so I'd have to go through the same motions as you would go through in trying to get it to work locally. I've just been deploying to heroku, happy to give you access to the heroku app.

**Comment by jhpoelen** [comment]
I've added some more instructions for running the app locally. I was able to successfully get things up and running. Memcache runs out of the box (at least did on my ubuntu machine). Hope this are easier now. Thanks for your patience.

**Comment by jhpoelen** [comment]
@paidforby please feel free to close this issue if you feel the issue has been addressed.

**Comment by paidforby** [comment]
Thanks for improving the readme, I'm still getting stuck at `foreman start` can't seem to find the foreman command. I'll try to figure out how to install foreman on debian. If it helps, for me `heroku -v` returns 
```
heroku-cli/6.16.3-4239951 (linux-x64) node-v9.9.0
```

**Comment by jhpoelen** [comment]
ok, did you try a search for "how to install foreman heroku" ?

**Comment by paidforby** [comment]
yeah, first result, https://devcenter.heroku.com/changelog-items/692
maybe that's the problem, but don't worry about it, I'll figure it out once I care enough.

**Comment by jhpoelen** [comment]
Once you start caring, please feel free to test the new install instructions.
