### ISSUE TITLE
route tables are cluttered

### ISSUE THREAD

**Issue by bennlich** [sudomesh/monitor#30]
They're a mix of current nodes and nodes we haven't seen in a long time. Current nodes should be at the top.

Simple fix would be to sort by time last seen (after sorting by ip).

Eventually we probably want to hide nodes that we haven't seen in, say, a month. Maybe behind some expandable section per exitnode, or just in an "old hat nodes" table at the bottom of the page.

We could also delete nodes from the DB that we haven't seen in a while.

**Comment by gobengo** [comment]
IMO we should also get rid of one-table-per-gateway and just have one big table with a 'gateway' column.

**Comment by bennlich** [comment]
@gobengo gateway === exitnode in this case?

**Comment by gobengo** [comment]
yaya

**Comment by bennlich** [comment]
sorting was added in https://github.com/sudomesh/monitor/commit/a2d2c73a98df829f8ef01b28adaaa899179ad3cc
