### ISSUE TITLE
What's the difference between `foreman start` and `heroku local www`?

### ISSUE THREAD

**Issue by eenblam** [sudomesh/monitor#4]
If they accomplish the same thing, can we drop foreman as a dependency?

**Comment by bennlich** [comment]
I already did the complement and removed heroku cli install from the readme, as I was able to run locally without :-P

**Comment by bennlich** [comment]
https://devcenter.heroku.com/articles/heroku-local#run-your-app-locally-using-foreman

**Comment by bennlich** [comment]
But yeah if you want to switch the foreman dep with heroku cli, I think that would be fine.
