### ISSUE TITLE
Clean cruft from original application

### ISSUE THREAD

**Issue by eenblam** [sudomesh/monitor#5]
Can we decruft some stuff from the old application, while also doing a better job of attributing it?

For example:
- [ ] I'm not sure how legit it is to distribute under GPL when `app.js` is MIT.
- [x] ~Is `bin/` cruft? Can we get rid of it (and the dependency on `debug`) in favor of `heroku local www`?~ Nevermind
- [x] Remove "Memcachier" stuff (fixed by 2e3f35fa55bbab282bb701216072df770e892e92)

More to come, maybe?

**Comment by bennlich** [comment]
`bin/` is referenced here: https://github.com/sudomesh/monitor/blob/master/Procfile, which is read by foreman, I believe.

**Comment by eenblam** [comment]
Yeah, spent the evening getting a better handle on how things are laid out.

`bin/` makes sense, and I didn't look hard enough at `debug` to realize it's actually just a logger. I'm too used to coming across Flask apps with debug mode enabled.

**Comment by eenblam** [comment]
This issue was quickly resolved; apologies for leaving it open.
